### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-duplicity#5]
CSIS Usage Documentation.

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by DenoBeno** [comment]
Is there some documentation that I am not aware of, or are you referring to tutorial PowerPoints?

**Comment by p-a-s-c-a-l** [comment]
> Is there some documentation that I am not aware of, or are you referring to tutorial PowerPoints?

I'm referring to [this documentation](https://github.com/clarity-h2020/docker-duplicity#clarity-docker-duplicity).
